name: bookmart
description: BookMart

publish_to: 'none'

version: 5.0.0+5

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  uuid: ^3.0.2
  firebase_core: ^1.0.3
  google_sign_in: ^5.2.1 # 4.5.9
  cupertino_icons: ^0.1.3
  firebase_auth: ^1.0.1
  provider: ^5.0.0
  flutter_spinkit: ^4.1.2+1
  animated_text_kit: ^3.1.0
  auth_buttons: ^0.0.4
  cloud_firestore: ^1.0.4
  curved_navigation_bar: ^0.3.7
  shared_preferences: ^2.0.5
  flutter_launcher_icons: ^0.9.0
  string_validator: ^0.3.0
  http: ^0.13.1
  cached_network_image: ^3.0.0
  groovin_widgets: ^1.6.0
  geolocator: ^7.0.1
  geocoder: ^0.2.1
  image_picker: ^0.7.3
  firebase_storage: ^8.0.1
  flutter_barcode_scanner: ^2.0.0-nullsafety.0
  path_provider: ^2.0.1
  algolia: ^1.0.1
  prompt_dialog: ^0.1.4
  profanity_filter: ^1.0.4
  email_validator: ^1.0.6
  sign_in_with_apple: ^3.3.0
  crypto: ^3.0.0
  google_mobile_ads: ^0.11.0+4
  flutter_native_splash: ^1.1.5+1
  firebase_messaging: ^9.1.0
  notification_permissions: ^0.4.8
  overlay_support: ^1.2.0
  flutter_local_notifications: ^5.0.0
  currency_picker: ^2.0.3
  share: ^2.0.1
  show_up_animation: ^2.0.0
  password_strength: ^0.2.0
  books_finder: ^4.1.0
  flutter_image_compress: ^1.0.0
  pattern_formatter: ^2.0.0
  dropdown_search: ^0.6.3
  pay: ^1.0.6
  material_floating_search_bar: ^0.3.6
  flutterwave_standard: 1.0.2
  intl_phone_number_input: ^0.7.0+2
  phone_number: ^0.12.0+1
  forex_conversion: ^0.0.3


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  image_path: "images/icon.png"
  android: true
  ios: true

flutter_native_splash:
  color: "#4fc3f7"
  color_dark: "#000000"
  image: "images/iphoneicon.png"

flutter:
  uses-material-design: true
  assets:
    - images/

  fonts:
    - family: Open Sans
      fonts:
        - asset: fonts/OpenSans-Light.ttf

    - family: Open Sans Bold
      fonts:
        - asset: fonts/OpenSans-Bold.ttf

    - family: Open Sans Regular
      fonts:
        - asset: fonts/OpenSans-Regular.ttf

    - family: Open Sans Semi Bold
      fonts:
        - asset: fonts/OpenSans-SemiBold.ttf

    - family: Poppins Bold
      fonts:
        - asset: fonts/Poppins-Bold.ttf

    - family: Poppins Regular
      fonts:
        - asset: fonts/Poppins-Regular.ttf